- examples/plugins/org.jboss.tools.project.examples/src/org/jboss/tools/project/examples/internal/UnArchiver.java
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> JBIDE-20052 : limit filtering depth when unzipping examples

- examples/plugins/org.jboss.tools.project.examples/src/org/jboss/tools/project/examples/model/AbstractImportProjectExample.java
- examples/plugins/org.jboss.tools.project.examples/src/org/jboss/tools/project/examples/model/ProjectExampleUtil.java
- examples/tests/org.jboss.tools.project.examples.test/src/org/jboss/tools/project/examples/model/ProjectExampleUtilTest.java
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> JBIDE-20111 : more robust way to get default examples directory

- central/features/org.jboss.tools.central.easymport.feature/feature.xml
+ use requires instead of includes
> JBIDE-19881: JSDT importer from upstream

- examples/plugins/org.jboss.tools.project.examples/src/org/jboss/tools/project/examples/internal/ProjectExamplesActivator.java
https://issues.jboss.org/browse/JBIDE-21022
open of .md files in project examples don't use markdown editor
> JBIDE-21022 - open of .md files in project examples don't use markdown editor

- maven/plugins/org.jboss.tools.maven.ui/src/org/jboss/tools/maven/ui/internal/markers/MavenDependencyMarkerResolutionGenerator.java
- maven/tests/org.jboss.tools.maven.common.test/projects/markers/p4/pom.xml
- maven/tests/org.jboss.tools.maven.common.test/src/org/jboss/tools/maven/ui/markers/MarkerResolutionTest.java
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> JBIDE-21827 : add marker for org.jboss.*.eap* groupids

- examples/plugins/org.jboss.tools.project.examples.cheatsheet/src/org/jboss/tools/project/examples/cheatsheet/internal/util/CheatSheetUtil.java
https://issues.jboss.org/browse/JBIDE-22041
Exception is thrown when I do not want to open cheatsheet
> JBIDE-22041 - Exception is thrown when I do not want to open cheatsheet

- .gitignore
JBIDE-23089 add hs_err_pid*.log to .gitignore
> JBIDE-23089 add hs_err_pid*.log to .gitignore

- pom.xml
> [JBIDE-23202] - For JBIDE 4.4.2.AM1: Prepare for 4.4.2.AM1 / 10.2.0.AM1 [Central]

- discovery/plugins/org.jboss.tools.discovery.core/src/org/jboss/tools/discovery/core/internal/connectors/xpl/ExternalBundleDiscoveryStrategy.java
- discovery/plugins/org.jboss.tools.discovery.core/src/org/jboss/tools/discovery/core/internal/connectors/xpl/RemoteExternalBundleDiscoveryStrategy.java
Signed-off-by: Jeff MAURY jmaury@redhat.com
> [JBIDE-22543] - Different errors when closing Central right after it was opened

- discovery/plugins/org.jboss.tools.discovery.core/src/org/jboss/tools/discovery/core/internal/connectors/PrepareInstallProfileJob.java
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
> JBIDE-24530 Set install wizard to block on open

- central/test-framework/org.jboss.tools.central.reddeer/src/org/jboss/tools/central/reddeer/wizards/JBossCentralProjectWizard.java
- maven/test-framework/org.jboss.tools.maven.reddeer/plugin.xml
- maven/test-framework/org.jboss.tools.maven.reddeer/src/org/jboss/tools/maven/reddeer/preferences/MavenUserPreferencePage.java
- maven/test-framework/org.jboss.tools.maven.reddeer/src/org/jboss/tools/maven/reddeer/profiles/SelectProfilesDialog.java
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-24943 Fixes for Maven Integration tests refactoring for RedDeer2

- central/test-framework/org.jboss.tools.central.reddeer/META-INF/MANIFEST.MF
> [JBIDE-25426] - central build is failing

- central/tests/org.jboss.tools.central.test/src/org/jboss/tools/central/internal/discovery/wizards/CachedProxyWizardDiscoveryStrategyTest.java
> [JBIDE-25435] - Fix intermittent failure in central tests

- examples/plugins/org.jboss.tools.project.examples/src/org/jboss/tools/project/examples/wizard/ImportDefaultProjectExample.java
> [JBIDE-25427] - Oxygen.2 TP

- maven/tests/org.jboss.tools.maven.configurators.tests/projects/springboot/jar/pom.xml
- maven/tests/org.jboss.tools.maven.configurators.tests/projects/springboot/war/pom.xml
- maven/tests/org.jboss.tools.maven.conversion.test/projects/conversion/JBIDE-13781/earClient/pom.xml
> [JBIDE-25705] - central unit test failures with Java9

- central/features/org.jboss.tools.central.easymport.feature/pom.xml
- central/features/org.jboss.tools.central.feature/feature.xml
- central/features/org.jboss.tools.central.feature/pom.xml
- central/features/org.jboss.tools.central.test.feature/feature.xml
- central/features/org.jboss.tools.central.test.feature/pom.xml
- central/features/org.jboss.tools.central.themes.feature/feature.xml
- central/features/org.jboss.tools.central.themes.feature/pom.xml
- central/features/org.jboss.tools.community.central.feature/feature.xml
- central/features/org.jboss.tools.community.central.feature/pom.xml
- central/features/pom.xml
- central/plugins/org.jboss.tools.central.themes/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.central.themes/pom.xml
- central/plugins/org.jboss.tools.central/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.central/plugin.properties
- central/plugins/org.jboss.tools.central/plugin.xml
- central/plugins/org.jboss.tools.central/pom.xml
- central/plugins/org.jboss.tools.community.central/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.community.central/pom.xml
- central/plugins/pom.xml
- central/pom.xml
- central/test-framework/org.jboss.tools.central.reddeer/META-INF/MANIFEST.MF
- central/test-framework/org.jboss.tools.central.reddeer/pom.xml
- central/test-framework/pom.xml
- central/tests/org.jboss.tools.central.test/META-INF/MANIFEST.MF
- central/tests/org.jboss.tools.central.test/pom.xml
- central/tests/pom.xml
> JBIDE-25770 JBIDE-25736 remove Hybrid Mobile Project wizard from Central

- central/plugins/org.jboss.tools.central/src/org/jboss/tools/central/internal/CentralHelper.java
- examples/features/org.jboss.tools.community.project.examples.feature/feature.xml
- examples/features/org.jboss.tools.community.project.examples.feature/pom.xml
- examples/features/org.jboss.tools.maven.project.examples.feature/feature.xml
- examples/features/org.jboss.tools.maven.project.examples.feature/pom.xml
- examples/features/org.jboss.tools.project.examples.feature/pom.xml
- examples/features/org.jboss.tools.project.examples.seam.feature/feature.xml
- examples/features/org.jboss.tools.project.examples.seam.feature/pom.xml
- examples/features/org.jboss.tools.project.examples.test.feature/feature.xml
- examples/features/org.jboss.tools.project.examples.test.feature/pom.xml
- examples/features/pom.xml
- examples/plugins/org.jboss.tools.community.project.examples/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.community.project.examples/pom.xml
- examples/plugins/org.jboss.tools.maven.project.examples/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.maven.project.examples/pom.xml
- examples/plugins/org.jboss.tools.project.examples.cheatsheet/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.project.examples.cheatsheet/pom.xml
- examples/plugins/org.jboss.tools.project.examples.seam/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.project.examples.seam/pom.xml
- examples/plugins/org.jboss.tools.project.examples/pom.xml
- examples/plugins/pom.xml
- examples/pom.xml
- examples/tests/org.jboss.tools.maven.examples.test/META-INF/MANIFEST.MF
- examples/tests/org.jboss.tools.maven.examples.test/pom.xml
- examples/tests/org.jboss.tools.project.examples.test/META-INF/MANIFEST.MF
- examples/tests/org.jboss.tools.project.examples.test/pom.xml
- examples/tests/pom.xml
Signed-off-by: Rob Stryker <rob@oxbeef.net>
> JBIDE-22713 - likely fix for bundled central webpage

- central/tests/org.jboss.tools.central.test/META-INF/MANIFEST.MF
> [JBIDE-25975] - Adapt central for Photon

- examples/features/org.jboss.tools.community.project.examples.feature/feature.xml
- examples/features/org.jboss.tools.community.project.examples.feature/pom.xml
- examples/features/org.jboss.tools.maven.project.examples.feature/feature.xml
- examples/features/org.jboss.tools.maven.project.examples.feature/pom.xml
- examples/features/org.jboss.tools.project.examples.feature/pom.xml
- examples/features/org.jboss.tools.project.examples.seam.feature/feature.xml
- examples/features/org.jboss.tools.project.examples.seam.feature/pom.xml
- examples/features/org.jboss.tools.project.examples.test.feature/feature.xml
- examples/features/org.jboss.tools.project.examples.test.feature/pom.xml
- examples/features/pom.xml
- examples/plugins/org.jboss.tools.community.project.examples/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.community.project.examples/pom.xml
- examples/plugins/org.jboss.tools.maven.project.examples/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.maven.project.examples/pom.xml
- examples/plugins/org.jboss.tools.project.examples.cheatsheet/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.project.examples.cheatsheet/pom.xml
- examples/plugins/org.jboss.tools.project.examples.cheatsheet/src/org/jboss/tools/project/examples/cheatsheet/internal/util/CheatSheetUtil.java
- examples/plugins/org.jboss.tools.project.examples.seam/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.project.examples.seam/pom.xml
- examples/plugins/org.jboss.tools.project.examples/pom.xml
- examples/plugins/pom.xml
- examples/pom.xml
- examples/tests/org.jboss.tools.maven.examples.test/META-INF/MANIFEST.MF
- examples/tests/org.jboss.tools.maven.examples.test/pom.xml
- examples/tests/org.jboss.tools.project.examples.test/META-INF/MANIFEST.MF
- examples/tests/org.jboss.tools.project.examples.test/pom.xml
- examples/tests/pom.xml
> [JBIDE-25915] - NullPointerException when not opening CheatSheet for imported project

- central/plugins/org.jboss.tools.central/src/org/jboss/tools/central/editors/GettingStartedHtmlPage.java
> [JBIDE-26137] - Central page should display more than 5 RSS entries

- examples/plugins/org.jboss.tools.maven.project.examples/src/org/jboss/tools/maven/project/examples/MavenProjectExamplesActivator.java
- examples/plugins/org.jboss.tools.project.examples/src/org/jboss/tools/project/examples/internal/UnArchiver.java
> [JBDS-4681] - Fuse examples from Red Hat Central view fail to install Fuse tooling from Central repository

- launcher/plugins/org.jboss.tools.common.launcher.ui/src/main/java/org/jboss/tools/common/launcher/ui/wizard/NewLauncherProjectWizard.java
> [JBIDE-26386] - Launcher project wizard does not create project

- launcher/features/org.jboss.tools.common.launcher.feature/feature.xml
- launcher/features/org.jboss.tools.common.launcher.feature/pom.xml
- launcher/features/pom.xml
- launcher/plugins/org.jboss.tools.common.launcher.core/META-INF/MANIFEST.MF
- launcher/plugins/org.jboss.tools.common.launcher.core/pom.xml
- launcher/plugins/org.jboss.tools.common.launcher.ui/META-INF/MANIFEST.MF
- launcher/plugins/org.jboss.tools.common.launcher.ui/pom.xml
- launcher/plugins/org.jboss.tools.common.launcher.ui/src/main/java/org/jboss/tools/common/launcher/ui/wizard/NewLauncherProjectModel.java
- launcher/plugins/pom.xml
- launcher/pom.xml
- launcher/tests/org.jboss.tools.common.launcher.core.test/META-INF/MANIFEST.MF
- launcher/tests/org.jboss.tools.common.launcher.core.test/pom.xml
- launcher/tests/org.jboss.tools.common.launcher.ui.test/META-INF/MANIFEST.MF
- launcher/tests/org.jboss.tools.common.launcher.ui.test/pom.xml
- launcher/tests/pom.xml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-26476 Fixing NPE in NewLauncherProjectModel

- central/tests/org.jboss.tools.central.test/META-INF/MANIFEST.MF
- examples/plugins/org.jboss.tools.project.examples/META-INF/MANIFEST.MF
- examples/tests/org.jboss.tools.project.examples.test/META-INF/MANIFEST.MF
- maven/plugins/org.jboss.tools.maven.core/META-INF/MANIFEST.MF
- maven/tests/org.jboss.tools.maven.common.test/META-INF/MANIFEST.MF
> JBIDE-26500 - central test errors on Java11+

- launcher/features/org.jboss.tools.common.launcher.feature/feature.xml
- launcher/features/org.jboss.tools.common.launcher.feature/pom.xml
- launcher/features/org.jboss.tools.common.launcher.test.feature/feature.xml
- launcher/features/org.jboss.tools.common.launcher.test.feature/pom.xml
- launcher/features/pom.xml
- launcher/plugins/org.jboss.tools.common.launcher.core/.project
- launcher/plugins/org.jboss.tools.common.launcher.core/META-INF/MANIFEST.MF
- launcher/plugins/org.jboss.tools.common.launcher.core/pom.xml
- launcher/plugins/org.jboss.tools.common.launcher.ui/.project
- launcher/plugins/org.jboss.tools.common.launcher.ui/META-INF/MANIFEST.MF
- launcher/plugins/org.jboss.tools.common.launcher.ui/pom.xml
- launcher/plugins/org.jboss.tools.common.launcher.ui/src/main/java/org/jboss/tools/common/launcher/ui/wizard/NewLauncherProjectWizardPage.java
- launcher/plugins/pom.xml
- launcher/pom.xml
- launcher/test-framework/org.jboss.tools.common.launcher.reddeer/META-INF/MANIFEST.MF
- launcher/test-framework/org.jboss.tools.common.launcher.reddeer/pom.xml
- launcher/test-framework/pom.xml
- launcher/tests/org.jboss.tools.common.launcher.core.test/META-INF/MANIFEST.MF
- launcher/tests/org.jboss.tools.common.launcher.core.test/pom.xml
- launcher/tests/org.jboss.tools.common.launcher.ui.test/META-INF/MANIFEST.MF
- launcher/tests/org.jboss.tools.common.launcher.ui.test/pom.xml
- launcher/tests/pom.xml
compilation error in Eclipse (only - weird enough maven wont complain for me):
**org.jboss.tools.common.launcher.ui.wizard.NewLauncherProjectWizardPage**
> The method create(String, IJobFunction) is ambiguous for the type Job	NewLauncherProjectWizardPage.java	/org.jboss.tools.common.launcher.ui/src/main/java/org/jboss/tools/common/launcher/ui/wizard	line 259
> fix compilation error in Eclipse

- central/test-framework/org.jboss.tools.central.reddeer/META-INF/MANIFEST.MF
- central/test-framework/org.jboss.tools.central.reddeer/src/org/jboss/tools/central/reddeer/utils/CentralUtils.java
Add the Utils class.
please review @jkopriva
Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>
> JBIDE-26903 - add the Utils class.

- central/features/org.jboss.tools.central.feature/feature.xml
- central/features/org.jboss.tools.central.feature/pom.xml
- central/features/org.jboss.tools.central.test.feature/feature.xml
- central/features/org.jboss.tools.central.test.feature/pom.xml
- central/features/org.jboss.tools.central.themes.feature/feature.xml
- central/features/org.jboss.tools.central.themes.feature/pom.xml
- central/features/org.jboss.tools.community.central.feature/feature.xml
- central/features/org.jboss.tools.community.central.feature/pom.xml
- central/features/pom.xml
- central/plugins/org.jboss.tools.central.themes/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.central.themes/pom.xml
- central/plugins/org.jboss.tools.central/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.central/pom.xml
- central/plugins/org.jboss.tools.community.central/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.community.central/pom.xml
- central/plugins/pom.xml
- central/pom.xml
- central/test-framework/org.jboss.tools.central.reddeer/META-INF/MANIFEST.MF
- central/test-framework/org.jboss.tools.central.reddeer/pom.xml
- central/test-framework/pom.xml
- central/tests/org.jboss.tools.central.test/META-INF/MANIFEST.MF
- central/tests/org.jboss.tools.central.test/pom.xml
- central/tests/pom.xml
> JBIDE-27372 : removed yedit from Target Platform

- launcher/test-framework/org.jboss.tools.common.launcher.reddeer/src/org/jboss/tools/common/launcher/reddeer/wizards/NewLauncherProjectWizard.java
- launcher/test-framework/org.jboss.tools.common.launcher.reddeer/src/org/jboss/tools/common/launcher/reddeer/wizards/NewLauncherProjectWizardPage.java
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-27646 Add new functions in NewLauncherProjectWizardPage.java

- launcher/test-framework/org.jboss.tools.common.launcher.reddeer/src/org/jboss/tools/common/launcher/reddeer/wizards/NewLauncherProjectWizard.java
**Jira:** https://issues.redhat.com/browse/JBIDE-27724
Please review @jkopriva or @odockal
> Fix the method for opening a wizard from shell menu

- maven/tests/org.jboss.tools.maven.configurators.tests/projects/jsf/jsf-deltaspike/pom.xml
> fix tests by using https

- central/features/pom.xml
- examples/features/pom.xml
- launcher/features/pom.xml
- maven/features/pom.xml
> use correct tycho source feature config

- central/plugins/org.jboss.tools.community.central/pom.xml
- examples/tests/org.jboss.tools.project.examples.test/pom.xml
- examples/tests/org.jboss.tools.project.examples.test/src/org/jboss/tools/project/examples/tests/ProjectTest.java
- maven/tests/org.jboss.tools.maven.sourcelookup.test/pom.xml
> JBIDE-26888 : Replace http access to https

- central/plugins/org.jboss.tools.central/src/org/jboss/tools/central/editors/xpl/DiscoveryViewer.java
> JBIDE-28506: Software page not showing up.

- central/features/org.jboss.tools.central.feature/feature.xml
- central/features/org.jboss.tools.central.feature/pom.xml
- central/features/org.jboss.tools.central.test.feature/feature.xml
- central/features/org.jboss.tools.central.test.feature/pom.xml
- central/features/org.jboss.tools.central.themes.feature/feature.xml
- central/features/org.jboss.tools.central.themes.feature/pom.xml
- central/features/org.jboss.tools.community.central.feature/feature.xml
- central/features/org.jboss.tools.community.central.feature/pom.xml
- central/features/pom.xml
- central/plugins/org.jboss.tools.central.themes/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.central.themes/pom.xml
- central/plugins/org.jboss.tools.central/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.central/pom.xml
- central/plugins/org.jboss.tools.central/src/org/jboss/tools/central/internal/CentralHelper.java
- central/plugins/org.jboss.tools.central/src/org/jboss/tools/central/internal/dnd/JBossCentralDropTarget.java
- central/plugins/org.jboss.tools.community.central/META-INF/MANIFEST.MF
- central/plugins/org.jboss.tools.community.central/pom.xml
- central/plugins/pom.xml
- central/pom.xml
- central/test-framework/org.jboss.tools.central.reddeer/META-INF/MANIFEST.MF
- central/test-framework/org.jboss.tools.central.reddeer/pom.xml
- central/test-framework/pom.xml
- central/tests/org.jboss.tools.central.test/META-INF/MANIFEST.MF
- central/tests/org.jboss.tools.central.test/pom.xml
- central/tests/pom.xml
> JBIDE-26888: update http url to https

- maven/test-framework/org.jboss.tools.maven.reddeer/src/org/jboss/tools/maven/reddeer/wizards/MavenProjectWizard.java
- maven/test-framework/org.jboss.tools.maven.reddeer/src/org/jboss/tools/maven/reddeer/wizards/MavenProjectWizardThirdPage.java
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
> Patch Maven Archetype generation in interactive mode in itests
